name: Build backend
on:
  push
  
jobs:
  Backend:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: create new folder dist and copy run.py in dist + insert comment line with build date
        run: |
          mkdir dist
          cp src/backend/run.py dist/
          sed -i '1i # $(date+ '%H:%M:%S')' dist/run.py
      - name: show python file
        run: cat dist/run.py
      - name: run python file
        run: python disty/run.py
        
