name: Build backend
on:
  push
  
jobs:
  Backend:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
